-- Drop the table if it exists to ensure a clean slate.
DROP TABLE IF EXISTS public.tbl_archivedalphauserdetails;

-- This table is a mirror of tbl_alphauserdetails and stores a complete historical
-- record of users who have been removed from the active user list.
CREATE TABLE public.tbl_archivedalphauserdetails (
    archived_at timestamp with time zone DEFAULT now(),
    _id text NOT NULL,
    _rev text,
    custom_regcompanyname text,
    frunindexedstring1 text,
    frunindexedstring2 text,
    frunindexedstring3 text,
    frunindexedstring4 text,
    frunindexedstring5 text,
    frindexedstring11 text,
    frindexedstring12 text,
    frindexedstring10 text,
    frindexedstring19 text,
    frindexedstring17 text,
    frindexedstring18 text,
    frindexedstring15 text,
    frindexedstring16 text,
    frindexedstring13 text,
    frindexedstring14 text,
    givenname text,
    frindexedstring20 text,
    telephonenumber text,
    city text,
    displayname text,
    accountstatus text,
    sn text,
    frunindexeddate1 timestamp without time zone,
    frindexedstring9 text,
    frindexedstring8 text,
    frindexedstring7 text,
    frindexedstring6 text,
    passwordlastchangedtime timestamp without time zone,
    country text,
    mail text,
    frindexeddate5 timestamp without time zone,
    frindexeddate4 timestamp without time zone,
    frindexeddate3 timestamp without time zone,
    frindexedstring5 text,
    frindexedstring4 text,
    frindexedstring3 text,
    frindexedstring2 text,
    frindexedstring1 text,
    frunindexedinteger3 integer,
    frunindexedinteger2 integer,
    frunindexedinteger1 integer,
    description text,
    frindexedinteger4 integer,
    frindexedinteger3 integer,
    frindexedinteger2 integer,
    frindexedinteger1 integer,
    frindexedinteger5 integer,
    username text,
    frindexeddate2 timestamp without time zone,
    frindexeddate1 timestamp without time zone,
    last_modified timestamp with time zone,
    operation_type character varying(10),
    PRIMARY KEY (_id, archived_at) -- Composite key to allow re-archiving
);

-- Set the owner of the table.
ALTER TABLE public.tbl_archivedalphauserdetails OWNER TO offboarding_user;