-- Create table for archived user details in PostgreSQL
CREATE TABLE tbl_ArchivedUserDetails (
    _id VARCHAR(100) PRIMARY KEY,
    _rev VARCHAR(100),
    custom_RegCompanyName VARCHAR(200),
    frUnindexedString1 VARCHAR(200),
    frUnindexedString2 VARCHAR(200),
    frUnindexedString3 VARCHAR(200),
    frUnindexedString4 VARCHAR(200),
    frUnindexedString5 VARCHAR(200),
    frIndexedString11 VARCHAR(200),
    frIndexedString12 VARCHAR(200),
    frIndexedString10 VARCHAR(200),
    frIndexedString19 VARCHAR(200),
    frIndexedString17 VARCHAR(200),
    frIndexedString18 VARCHAR(200),
    frIndexedString15 VARCHAR(200),
    frIndexedString16 VARCHAR(200),
    frIndexedString13 VARCHAR(200),
    frIndexedString14 VARCHAR(200),
    givenName VARCHAR(200),
    frIndexedString20 VARCHAR(200),
    telephoneNumber VARCHAR(50),
    city VARCHAR(100),
    displayName VARCHAR(200),
    accountStatus VARCHAR(50),
    sn VARCHAR(200),
    frUnindexedDate1 VARCHAR(50),
    frIndexedString9 VARCHAR(200),
    frIndexedString8 VARCHAR(200),
    frIndexedString7 VARCHAR(200),
    frIndexedString6 VARCHAR(200),
    passwordLastChangedTime VARCHAR(50),
    country VARCHAR(100),
    mail VARCHAR(200),
    frIndexedDate5 VARCHAR(50),
    frIndexedDate4 VARCHAR(50),
    frIndexedDate3 VARCHAR(50),
    frIndexedString5 VARCHAR(200),
    frIndexedString4 VARCHAR(200),
    frIndexedString3 VARCHAR(200),
    frIndexedString2 VARCHAR(200),
    frIndexedString1 VARCHAR(200),
    frUnindexedInteger3 INT,
    frUnindexedInteger2 INT,
    frUnindexedInteger1 INT,
    description TEXT,
    frIndexedInteger4 INT,
    frIndexedInteger3 INT,
    frIndexedInteger2 INT,
    frIndexedInteger1 INT,
    frIndexedInteger5 INT,
    userName VARCHAR(200),
    frIndexedDate2 VARCHAR(50),
    frIndexedDate1 VARCHAR(50),
    deletion_count INT DEFAULT 1,
    first_deleted_at TIMESTAMP DEFAULT NOW(),
    last_deleted_at TIMESTAMP DEFAULT NOW()
);