-- Drop the table if it exists to ensure a clean slate
DROP TABLE IF EXISTS tbl_alphauserdetails;

-- Create table for active user details in PostgreSQL
CREATE TABLE tbl_AlphaUserDetails (
    _id TEXT PRIMARY KEY,
    _rev TEXT,
    custom_RegCompanyName TEXT,
    frUnindexedString1 TEXT,
    frUnindexedString2 TEXT,
    frUnindexedString3 TEXT,
    frUnindexedString4 TEXT,
    frUnindexedString5 TEXT,
    frIndexedString11 TEXT,
    frIndexedString12 TEXT,
    frIndexedString10 TEXT,
    frIndexedString19 TEXT,
    frIndexedString17 TEXT,
    frIndexedString18 TEXT,
    frIndexedString15 TEXT,
    frIndexedString16 TEXT,
    frIndexedString13 TEXT,
    frIndexedString14 TEXT,
    givenName TEXT,
    frIndexedString20 TEXT,
    telephoneNumber TEXT,
    city TEXT,
    displayName TEXT,
    accountStatus TEXT,
    sn TEXT,
    frUnindexedDate1 TIMESTAMP,
    frIndexedString9 TEXT,
    frIndexedString8 TEXT,
    frIndexedString7 TEXT,
    frIndexedString6 TEXT,
    passwordLastChangedTime TIMESTAMP,
    country TEXT,
    mail TEXT,
    frIndexedDate5 TIMESTAMP,
    frIndexedDate4 TIMESTAMP,
    frIndexedDate3 TIMESTAMP,
    frIndexedString5 TEXT,
    frIndexedString4 TEXT,
    frIndexedString3 TEXT,
    frIndexedString2 TEXT,
    frIndexedString1 TEXT,
    frUnindexedInteger3 INTEGER,
    frUnindexedInteger2 INTEGER,
    frUnindexedInteger1 INTEGER,
    description TEXT,
    frIndexedInteger4 INTEGER,
    frIndexedInteger3 INTEGER,
    frIndexedInteger2 INTEGER,
    frIndexedInteger1 INTEGER,
    frIndexedInteger5 INTEGER,
    userName TEXT,
    frIndexedDate2 TIMESTAMP,
    frIndexedDate1 TIMESTAMP
);